### ISSUE TITLE
Circus doesnt seem to send SIGTERM properly

### ISSUE THREAD

**Issue by evanccnyc** [circus-tent/circus#923] opened 2015-09-01 18:32 UTC
Maybe I am missing something obvious but I cant get circus to send sigterms on stop or restart. I have tested this on multiple applications, (written in python and go) but have created a test case below:

Tested with a clean box and circusctl 0.12.1.

Below is the testcase:

test.ini
``` 
[watcher:test]
cmd = python test2.py > /var/log/circus/test2.log
args =
working_dir = /home/vagrant/
shell=True
numprocesses = 1
uid = vagrant
gid = users
respawn = True
```

test2.py
```
from threading import Thread
import time, sys, signal

shutdown_flag = False #used for gracefull shutdown

def main_loop():
    while not shutdown_flag:
#        collect_data() # contains some print "data" statements
        time.sleep(5)
        import threading
        print threading.enumerate()
    print "done (killed)"
def sighandler(signum, frame):
    print 'signal handler called with signal: %s ' % signum
    global shutdown_flag
    shutdown_flag = True
    sys.exit() # make sure you add this so the main thread exits as well.

def main(argv=None):
    signal.signal(signal.SIGTERM, sighandler) # so we can handle kill gracefully
    signal.signal(signal.SIGINT, sighandler) # so we can handle ctrl-c
    try:
        Thread(target=main_loop, args=()).start()
    except Exception, reason:
        print reason

if __name__ == '__main__':
    main(sys.argv)
    while 1:  # this will force your main thread to live until you terminate it.
       time.sleep(1)
```

When I send a SIGTERM via kill the command the log shows the following:
```
[<_MainThread(MainThread, started 139682171225920)>, <Thread(Thread-1, started 139682151667456)>]
[<_MainThread(MainThread, started 139682171225920)>, <Thread(Thread-1, started 139682151667456)>]
[<_MainThread(MainThread, started 139682171225920)>, <Thread(Thread-1, started 139682151667456)>]
[<_MainThread(MainThread, started 139682171225920)>, <Thread(Thread-1, started 139682151667456)>]
signal handler called with signal: 15
[<_MainThread(MainThread, stopped 139682171225920)>, <Thread(Thread-1, started 139682151667456)>]
done (killed)
```

When I run "circusctl restart test" nothing is printed out in the logs, showing it never received it. Let me know if I a missing something obvious.

**Comment by davidbirdsong** [comment] 2015-09-01 18:38
> signal handler called with signal: 15

your signal handler is getting called on SIGTERM right there.

**Comment by evanccnyc** [comment] 2015-09-01 18:40
@davidbirdsong that is when I send a sigterm via the kill command. Not when I run "circusctl restart test"

**Comment by davidbirdsong** [comment] 2015-09-01 18:48
Got it--I missed that. 

try adding:
```ini
singleton = True
```
so that circus doesn't start a new proc before signaling the old.

Also, when I'm trying to make sense of these things, I usually print to stderr to avoid buffering on stdout which can confuse humans reading log files.

**Comment by davidbirdsong** [comment] 2015-09-01 18:52
Last thing and I'm not 100% on this, but there might be some funny business in calling ```sys.exit``` from within your signal handler.

I can't claim too much expertise here, but it's my understanding that not much should be done inside a handler since there's a whole slew of stack jumping that goes on under the hood--better to only set global vars and act on them outside of that block.

**Comment by evanccnyc** [comment] 2015-09-01 18:55
Yeah, this test case is something I just threw together, we are seeing this on both python apps and go apps (the restarts worked before in 0.9.2 so they did work at some point). 

I tried with Singleton and it seems to have the same problem.

**Comment by k4nar** [comment] 2015-09-02 16:09
I just tried with a simpler testcase:

```python
import time
import signal

def sighandler(signum, frame):
    print("Received ", signum)
    exit()

    
signal.signal(signal.SIGTERM, sighandler)
signal.signal(signal.SIGINT, sighandler)
    
while True:
    print("sleeping")
    time.sleep(1)
```

`Received 15` do get printed every time I use `circusctl restart` or `circusctl stop`, so I don't see any issue here.
Do you reproduce with this testcase?

**Comment by evanccnyc** [comment] 2015-09-08 14:23
Sorry for the delay, I was dealing with other issues.  The testcase doesnt seem to be print out anything for me. What is your test.ini?

**Comment by k4nar** [comment] 2015-09-09 16:26
My .ini was very simple, something like that:

```ini
[watcher:test]
cmd = python test.py
```

**Comment by evanccnyc** [comment] 2015-09-09 18:24
After some additional testing when I set my ini to this and use your testcase it never receives the SIGTERMs:

```
[watcher:test2]
cmd = python /home/vagrant/test3.py
uid = vagrant
respawn = True
shell=True
numprocesses = 1
```

**Comment by k4nar** [comment] 2015-09-10 08:27
Sorry, I cannot reproduce. When I launch `circusctl restart test2`, `Received 15` does get printed and the watcher is restarted.

**Comment by evanccnyc** [comment] 2015-09-10 16:15
I am using Ubuntu 14.04, I have a vagrant file that pulls down   config.vm.box = "ubuntu1404". We have seen this on Ubuntu 14.04 in AWS as well.

**Comment by josegonzalez** [comment] 2015-09-22 17:06
To make what we are seeing a bit more clear, here is a reproduction as [a vagrant repository](https://github.com/josegonzalez/circus-sigterm). The readme lays out exactly what is happening, and I've taken the liberty of catching *all* signals in case circus is sending the wrong one.

I think circus might be sending a `SIGTERM` to the process that is _watching_ our process, and that is sending a SIGKILL to the underlying process - meaning it wouldn't be caught by our process. Quite lame, as that would mean we would need to use the `before_signal` hook to do anything useful (like attempt to save application state or terminate gracefully).

**Comment by k4nar** [comment] 2015-09-22 21:46
Thank you very much for this thorough test case, I'll take a look as soon as possible.

**Comment by josegonzalez** [comment] 2015-10-12 18:02
:bump:

**Comment by k4nar** [comment] 2015-10-26 09:18
Sorry for the delay. I confirm that I can reproduce your issue with the vagrant image. I'll try to see what's happening.

**Comment by josegonzalez** [comment] 2016-04-09 05:58
So false-ish alarm. I worked on this a bit more out of boredom. Turns out signals *are* being handled, but the way circus does restarts means that it drops the watcher immediately, without waiting for logging output to be captured and send to the write circus logstream.

Not sure what signal the restart sends, but triggering a `circusctl restart WATCHER` is similar to:

```shell
circusctl signal test 15 # SIGTERM
```

Whereas the desired output would be more like the following:

```shell
circusctl signal test 15 --children # SIGTERM
```

Assuming the `SIGTERM` signal is handled properly in the child, circus will create a new watcher, same as it would with a `circusctl restart`, except that logging output is handled properly, which is almost certainly less confusing to the user.

I've documented the above in my updated readme, and confirmed that this is the case for both `0.12.1` and `0.13`. The semantics of restarts probably changed sometime before 0.12, resulting in this somewhat perplexing output.

Thoughts?

**Comment by k4nar** [comment] 2016-04-25 13:20
I'm still a bit puzzled by this issue :) . I did some investigations but I wasn't able to find anything fishy. I did reproduce the issue in the vagrant but not on my own system.

As you seem to have solved your issue, I'm gonna close it. If anyone comes with a similar problem I'll re-open it.

**Closed by k4nar** 2016-04-25 13:20 UTC
