### ISSUE TITLE
Problem setting up circus web as NGINX reverseproxy

### ISSUE THREAD

**Issue by ondoheer** [circus-tent/circus#839] opened 2014-10-10 16:26 UTC
Hello, 

I started using Circus yesterday on my remote linode sever (ubuntu 12.10), I found it really easy to setup and use to run all my webapps in an orderly manner. 

The problem I have now is that I cannot seem to be able to setup the web client.
I'm running it behind nginx as a proxy using the standard documentation setup

I have tried the following setups, the circus config setup 

    [circus]
    httpd = True
    httpd_host = localhost
    httpd_port = 8080

web worker setup.

    [watcher:webconsole]
    env = /home/ondoheer/.virtualenvs/circus/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
    copy_env = True
    copy_path = True
    use_sockets = True
    singleton = True

    cmd = chaussette --fd $(circus.sockets.webcon) --backend 'tornado' circusweb.circushttpd.app

    [socket:webcon]
    host = 127.0.0.1
    port = 8080

When doing this I had to set tornado as --backend because with the standard wsgiref it raced and exception when using curl internally (with tornado it just doens't answer anything to the curl command, asme as with wverything else I tried).

    INFO:chaussette:Using <class chaussette.backend._wsgiref.ChaussetteServer at 0x228a8d8> as          a backend
    Traceback (most recent call last):
    File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
         self.result = application(self.environ, self.start_response)
    TypeError: __call__() takes exactly 2 arguments (3 given)
    0.0.0.0 - - [10/Oct/2014 16:22:54] "GET / HTTP/1.1" 500 59

and also
circushttpd which runs on 0.0.0.0:8080

the problem I'm getting is that conected to the linode machine I don't get any curl replies in any way, and when I try to connect to the subdomain I setup for the port and process it just redirects me to the default page served by nginx.

The only thing I changed was the server_name to point to the subdomain.

thanks a lot!

**Comment by cgarciaarano** [comment] 2015-06-03 17:03
Try to run chaussette outside Circus, just to check where the problem is. The socket _webcon_ declared in Circus configuration should be disabled

```
chaussette --host 127.0.0.1 --port 8080  --backend 'tornado' circusweb.circushttpd.app 
```
If the problem persists, run chaussette in a reachable IP to bypass Nginx.

**Comment by k4nar** [comment] 2016-06-12 14:32
I'm closing this issues as the question is almost 2 years old now. Please re-open if needed.

**Closed by k4nar** 2016-06-12 14:32 UTC
Labels: Question
